package main.java.data.datahandler;

import java.io.FileNotFoundException;
import java.io.IOException;

import main.java.author.model.GameBlueprint;

/**
 * 
 * Data Handler specific to the authoring environment.
 * Allows them to easily translate the blueprint
 * generated by the author into a JSON. 
 * Also allows for reverse functionality so that
 * they can take in a half created authoring file (JSON),
 * extract the info into a Blueprint so that they can
 * finish/add to their game.
 * 
 * @author Jimmy Fang
 *
 */

public class AuthorDataHandler extends DataHandler {

	public AuthorDataHandler(){
		super();
	}

	/**
	 * Exposed API method for authoring environment to
	 * take a blueprint and file location and serialize
	 * into a JSON file.
	 * @param currentBlueprint
	 * @param filePath
	 * @throws IOException 
	 */
	public void saveBlueprint(GameBlueprint currentBlueprint, String filePath) throws IOException {
		saveBundle(new DataBundle(currentBlueprint), filePath);
	}
	
	
	/**
	 * 
	 * @param filePath
	 * @return translate a JSON file into a GameBlueprint
	 * so that authoring environment can allow user to 
	 * load half creating environments and modify
	 * them
	 * @throws IOException 
	 * @throws ClassNotFoundException 
	 */
	public GameBlueprint loadBlueprint(String filePath) throws ClassNotFoundException, IOException {
		return loadBundle(filePath).getBlueprint();
	}
}
